// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://npzpkvvsumfaghshxpyl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5wenBrdnZzdW1mYWdoc2h4cHlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM3Njg5NDksImV4cCI6MjA4OTM0NDk0OX0.lQuUmIXIUHfJUCe-wwFswJIZxMuIzxLvVXI77b9l4U0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});