// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yrnrjbrzlzyvnyccsmcc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlybnJqYnJ6bHp5dm55Y2NzbWNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ0NjUzMDYsImV4cCI6MjA5MDA0MTMwNn0.hWR5npxin82Y_Mr_NWz5H8H-nLk_tNbizjESHVICLH8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});